"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var TransactionType;
(function (TransactionType) {
    TransactionType[TransactionType["RegisterSBP"] = 1] = "RegisterSBP";
    TransactionType[TransactionType["UpdateSBPBlockProducingAddress"] = 2] = "UpdateSBPBlockProducingAddress";
    TransactionType[TransactionType["UpdateSBPRewardWithdrawAddress"] = 3] = "UpdateSBPRewardWithdrawAddress";
    TransactionType[TransactionType["RevokeSBP"] = 4] = "RevokeSBP";
    TransactionType[TransactionType["WithdrawSBPReward"] = 5] = "WithdrawSBPReward";
    TransactionType[TransactionType["VoteForSBP"] = 6] = "VoteForSBP";
    TransactionType[TransactionType["CancelSBPVoting"] = 7] = "CancelSBPVoting";
    TransactionType[TransactionType["StakeForQuota"] = 8] = "StakeForQuota";
    TransactionType[TransactionType["CancelQuotaStake"] = 9] = "CancelQuotaStake";
    TransactionType[TransactionType["IssueToken"] = 10] = "IssueToken";
    TransactionType[TransactionType["ReIssueToken"] = 11] = "ReIssueToken";
    TransactionType[TransactionType["BurnToken"] = 12] = "BurnToken";
    TransactionType[TransactionType["TransferTokenOwnership"] = 13] = "TransferTokenOwnership";
    TransactionType[TransactionType["DisableReIssue"] = 14] = "DisableReIssue";
    TransactionType[TransactionType["CreateContractRequest"] = 15] = "CreateContractRequest";
    TransactionType[TransactionType["TransferRequest"] = 16] = "TransferRequest";
    TransactionType[TransactionType["ReIssueRequest"] = 17] = "ReIssueRequest";
    TransactionType[TransactionType["Response"] = 18] = "Response";
    TransactionType[TransactionType["ResponseFail"] = 19] = "ResponseFail";
    TransactionType[TransactionType["RefundByContractRequest"] = 20] = "RefundByContractRequest";
    TransactionType[TransactionType["GenesisResponse"] = 21] = "GenesisResponse";
    TransactionType[TransactionType["RegisterSBP_V1"] = 22] = "RegisterSBP_V1";
    TransactionType[TransactionType["UpdateSBPBlockProducingAddress_V1"] = 23] = "UpdateSBPBlockProducingAddress_V1";
    TransactionType[TransactionType["UpdateSBPBlockProducingAddress_V2"] = 24] = "UpdateSBPBlockProducingAddress_V2";
    TransactionType[TransactionType["RevokeSBP_V1"] = 25] = "RevokeSBP_V1";
    TransactionType[TransactionType["RevokeSBP_V2"] = 26] = "RevokeSBP_V2";
    TransactionType[TransactionType["WithdrawSBPReward_V1"] = 27] = "WithdrawSBPReward_V1";
    TransactionType[TransactionType["WithdrawSBPReward_V2"] = 28] = "WithdrawSBPReward_V2";
    TransactionType[TransactionType["VoteForSBP_V1"] = 29] = "VoteForSBP_V1";
    TransactionType[TransactionType["CancelSBPVoting_V1"] = 30] = "CancelSBPVoting_V1";
    TransactionType[TransactionType["StakeForQuota_V1"] = 31] = "StakeForQuota_V1";
    TransactionType[TransactionType["StakeForQuota_V2"] = 32] = "StakeForQuota_V2";
    TransactionType[TransactionType["CancelQuotaStake_V1"] = 33] = "CancelQuotaStake_V1";
    TransactionType[TransactionType["CancelQuotaStake_V2"] = 34] = "CancelQuotaStake_V2";
    TransactionType[TransactionType["IssueToken_V1"] = 35] = "IssueToken_V1";
    TransactionType[TransactionType["ReIssueToken_V1"] = 36] = "ReIssueToken_V1";
    TransactionType[TransactionType["TransferTokenOwnership_V1"] = 37] = "TransferTokenOwnership_V1";
    TransactionType[TransactionType["DisableReIssue_V1"] = 38] = "DisableReIssue_V1";
    TransactionType[TransactionType["DexDeposit_V1"] = 39] = "DexDeposit_V1";
    TransactionType[TransactionType["DexWithdraw_V1"] = 40] = "DexWithdraw_V1";
    TransactionType[TransactionType["DexPlaceOrder_V1"] = 41] = "DexPlaceOrder_V1";
    TransactionType[TransactionType["DexCancelOrder_V1"] = 42] = "DexCancelOrder_V1";
    TransactionType[TransactionType["DexOpenNewMarket_V1"] = 43] = "DexOpenNewMarket_V1";
    TransactionType[TransactionType["DexStakeForMining_V1"] = 44] = "DexStakeForMining_V1";
    TransactionType[TransactionType["DexStakeForVIP_V1"] = 45] = "DexStakeForVIP_V1";
    TransactionType[TransactionType["DexBindInviteCode_V1"] = 46] = "DexBindInviteCode_V1";
    TransactionType[TransactionType["DexCreateNewInviter_V1"] = 47] = "DexCreateNewInviter_V1";
    TransactionType[TransactionType["DexTransferTokenOwnership_V1"] = 48] = "DexTransferTokenOwnership_V1";
    TransactionType[TransactionType["DexMarketAdminConfig_V1"] = 49] = "DexMarketAdminConfig_V1";
    TransactionType[TransactionType["DexStakeForSuperVIP_V1"] = 50] = "DexStakeForSuperVIP_V1";
    TransactionType[TransactionType["DexConfigMarketAgents_V1"] = 51] = "DexConfigMarketAgents_V1";
    TransactionType[TransactionType["DexDeposit"] = 52] = "DexDeposit";
    TransactionType[TransactionType["DexWithdraw"] = 53] = "DexWithdraw";
    TransactionType[TransactionType["DexPlaceOrder"] = 54] = "DexPlaceOrder";
    TransactionType[TransactionType["DexCancelOrder"] = 55] = "DexCancelOrder";
    TransactionType[TransactionType["DexOpenNewMarket"] = 56] = "DexOpenNewMarket";
    TransactionType[TransactionType["DexStakeForMining"] = 57] = "DexStakeForMining";
    TransactionType[TransactionType["DexStakeForVIP"] = 58] = "DexStakeForVIP";
    TransactionType[TransactionType["DexBindInviteCode"] = 59] = "DexBindInviteCode";
    TransactionType[TransactionType["DexCreateNewInviter"] = 60] = "DexCreateNewInviter";
    TransactionType[TransactionType["DexTransferTokenOwnership"] = 61] = "DexTransferTokenOwnership";
    TransactionType[TransactionType["DexMarketAdminConfig"] = 62] = "DexMarketAdminConfig";
    TransactionType[TransactionType["DexStakeForSuperVIP"] = 63] = "DexStakeForSuperVIP";
    TransactionType[TransactionType["DexConfigMarketAgents"] = 64] = "DexConfigMarketAgents";
    TransactionType[TransactionType["DexLockVxForDividend"] = 65] = "DexLockVxForDividend";
    TransactionType[TransactionType["DexSwitchConfig"] = 66] = "DexSwitchConfig";
    TransactionType[TransactionType["DexStakeForPrincipalSVIP"] = 67] = "DexStakeForPrincipalSVIP";
    TransactionType[TransactionType["DexCancelStakeById"] = 68] = "DexCancelStakeById";
})(TransactionType = exports.TransactionType || (exports.TransactionType = {}));
var BlockType;
(function (BlockType) {
    BlockType[BlockType["CreateContractRequest"] = 1] = "CreateContractRequest";
    BlockType[BlockType["TransferRequest"] = 2] = "TransferRequest";
    BlockType[BlockType["ReIssueRequest"] = 3] = "ReIssueRequest";
    BlockType[BlockType["Response"] = 4] = "Response";
    BlockType[BlockType["ResponseFail"] = 5] = "ResponseFail";
    BlockType[BlockType["RefundByContractRequest"] = 6] = "RefundByContractRequest";
    BlockType[BlockType["GenesisResponse"] = 7] = "GenesisResponse";
})(BlockType = exports.BlockType || (exports.BlockType = {}));
